#!/usr/bin/env bash

CLHEP_DIR=CLHEP
BUILD_DIR=CLHEP-build
INSTALL_DIR=CLHEP-lib
LIB_DIR=$PWD
CLHEP_DIR_PATH=$PWD/$CLHEP_DIR
BUIL_DIR_PATH=$PWD/$BUILD_DIR
INSTALL_DIR_PATH=$PWD/$INSTALL_DIR

# build CLHEP
mkdir $BUIL_DIR_PATH
cd $BUIL_DIR_PATH
cmake -DCMAKE_INSTALL_PREFIX=$INSTALL_DIR_PATH $CLHEP_DIR_PATH
make -j
make install
cd $LIB_DIR
